# -*- coding: utf-8 -*-
"""TEST_ICT_DT_Arunima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vh1ljJEFlJhyQXvY3UFyPjOwZN87JnFQ
"""

import pandas as pd

# load data
data_train = pd.read_csv("/content/train_LZdllcl.csv")
data_test  = pd.read_csv("/content/test_2umaH9m.csv")

"""Exploratory Data Analysis"""

# display data
data_train.head()

# display data
data_test.head()

data_train.info()

data_test.info()

data_train.describe()

data_test.describe()

"""  Splitting into Features and Target"""

X = data_train.drop(columns=["is_promoted","employee_id"])  # employer id is a unique number and has no correlation with being promoted hence removed

X.head(5)  # FEATURES

X.shape

y = data_train["is_promoted"] #TARGET

y

y.shape

y.value_counts()   # Imbalanced data

# Visualize distribution
import matplotlib.pyplot as plt
import seaborn as sns
sns.countplot(x=y)
plt.show()

X_test = data_test.drop(columns=["employee_id"])    # Given Testing data

"""Preprocessing"""

# check duplicates in test data
X.duplicated().sum()  # no duplicates

#check duplictes in train data
X_test.duplicated().sum()  # no duplicates

#checking missing values in testing data
X.isnull().mean()*100

# check missing value in train data
X_test.isnull().mean()*100

# divide numerical columns and categorical columns

num_cols_x = X.select_dtypes(exclude="object").columns
cat_cols_x = X.select_dtypes(include="object").columns

# handling missing values in train data
from sklearn.impute import SimpleImputer #imputing categorical columns with mode
cat_imputer = SimpleImputer(strategy="most_frequent")

X[cat_cols_x] = cat_imputer.fit_transform(X[cat_cols_x])
X_test[cat_cols_x] = cat_imputer.fit_transform(X_test[cat_cols_x])

# Imputing numerical columns with median
num_imputer = SimpleImputer(strategy="median")

X[num_cols_x] = num_imputer.fit_transform(X[num_cols_x])
X_test[num_cols_x] = num_imputer.fit_transform(X_test[num_cols_x])

X.isna().mean()*100        # train data

X_test.isnull().mean()*100    #test data

# Outliers detection using Visualization - Box plot
# Plotting box plots for Numerical columns for train data
for col in num_cols_x:
    plt.figure(figsize=(6,4))
    sns.boxplot(y=X[col], color='Orange')
    plt.title(f'Boxplot of {col}')
    plt.show()

# Plotting box plots for Numerical columns for test data
for col in num_cols_x:
    plt.figure(figsize=(6,4))
    sns.boxplot(y=X_test[col], color='purple')
    plt.title(f'Boxplot of {col}')
    plt.show()

# we have defined a function for capping outiers

def cap_outliers_numeric(df, numeric_cols):
    """
    Caps outliers in all numeric columns using 1.5*IQR method.
    Modifies the DataFrame in-place to avoid SettingWithCopyWarning.
    """
    for col in numeric_cols:                   #calculate IQR
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1

        lower_limit = Q1 - 1.5 * IQR          #define limits
        upper_limit = Q3 + 1.5 * IQR

        # Use .loc to modify safely
        df.loc[:, col] = df[col].clip(lower_limit, upper_limit)   #Replace values

# calling the above defined function
cap_outliers_numeric(X, num_cols_x)
cap_outliers_numeric(X_test, num_cols_x)

# Plotting box plots for Numerical columns after outlier handling
for col in num_cols_x:
    plt.figure(figsize=(6,4))
    sns.boxplot(y=X[col], color='Pink')
    plt.title(f'Boxplot of {col}')
    plt.show()

# Plotting box plots for Numerical columns after outlier Handling
for col in num_cols_x:
    plt.figure(figsize=(6,4))
    sns.boxplot(y=X_test[col], color='blue')
    plt.title(f'Boxplot of {col}')
    plt.show()

# encoding

#Taking columns for one hot encoding
oe_cols= [ 'department', 'education', 'gender', 'recruitment_channel']

# One-Hot Encoding for training and test data
X = pd.get_dummies(X,columns=oe_cols,drop_first=True, dtype=int)
X_test = pd.get_dummies(X_test,columns=oe_cols,drop_first=True, dtype=int)

# Target encoding "region"
region_target_mean = X.join(y).groupby('region')['is_promoted'].mean()

X['region_enc'] = X['region'].map(region_target_mean)
X_test['region_enc'] = X_test['region'].map(region_target_mean).fillna(y.mean())

X = X.drop(columns=["region"],axis=1)
X_test = X_test.drop(columns=["region"],axis=1)

X.head(5)

X_test.head(5)

#Scaling
# scaling training and testing data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X[num_cols_x] = scaler.fit_transform(X[num_cols_x])
X_test[num_cols_x] = scaler.fit_transform(X_test[num_cols_x])

"""Handling Class Imbalance"""

# Find CIR ratio
y.value_counts()

maj_cls = y.value_counts().max()
min_cls = y.value_counts().min()
ratio = maj_cls / min_cls

print(f"Class Imbalance Ratio: {ratio:.2f}")   # target class is imbalanced

# Using SMOTE to handle imbalance

from imblearn.over_sampling import SMOTE

X.shape

y.shape

# Apply SMOTE
smote = SMOTE(sampling_strategy='auto')
X, y = smote.fit_resample(X, y)

sns.countplot(x=y)  # After applying Smote class is balanced
plt.show()

from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2, random_state = 42)

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#dt_model = DecisionTreeClassifier(random_state=42)
#dt_model.fit(X_train, y_train)
#y_pred_dt = dt_model.predict(X_val)

# Tuning
from sklearn.model_selection import GridSearchCV
param_grid = { "max_depth": [ None,3,5,7,10],"min_samples_split":[2,5,10],"criterion":["gini","entropy"]}

grid= GridSearchCV(DecisionTreeClassifier(random_state=42),param_grid,cv=10,scoring="accuracy")
grid.fit(X_train, y_train)

best_dt = grid.best_estimator_

train_acc_dt= best_dt.score(X_train,y_train)
val_acc_dt= best_dt.score(X_val,y_val)

# Best Parameters
print("Best PARAMS:", grid.best_params_)

# predictions
y_pred_dt_val = best_dt.predict(X_val)
y_pred_dt_train = best_dt.predict(X_train)

# Accuracy Scores
print("train_accuracy :",train_acc_dt)
print("Val_accuracy :",val_acc_dt)

# F1 Score
from sklearn.metrics import f1_score

f1_Val = f1_score(y_val, y_pred_dt_val)
print("F1 Score Val:", f1_Val)

f1_train = f1_score(y_train, y_pred_dt_train)
print("F1 Score Train:", f1_train)

# Classification Report
cr = classification_report(y_val, y_pred_dt_val)
print("Classification Report:")
print(cr)

# Confusion Matrix
cm=confusion_matrix(y_val, y_pred_dt_val)
print("Confusion Matrix:")
print(cm)

# Predicting on test data
y_test_pred = dt_model.predict(X_test)

y_test_pred  # predictions
predicted_column = pd.DataFrame({'predicted_label': y_test_pred})
predicted_column

# Make a dataframe with employee id and predictions
X_Solution = pd.DataFrame(data_test["employee_id"])
X_Solution["is_promoted"] = predicted_column
X_Solution

# Final file
X_Solution

# Generate csv file
X_Solution.to_csv('submission_dt.csv', index=False)